### PR TITLE
Add support for post-login message

### PR DESCRIPTION
**Pull request by bge-kernel-panic**
Hello,

In our company's juniper network setup, there's a "post login" message (a legal disclaimer) that gets shown after the initial login request.  It is then necessary to re-submit to login.do with a given hidden parameter (named "key") to continue with the actual login request.

The code I added to do this is rather ugly, but it seems to work well.

It may be advisable to grab the disclaimer from the HTML response and try to print it to the screen, but I find it's not needed for my own use :)

Feel free to remove the bunch of commented-out print statements I used while debugging (I wasn't that familiar with elementtree :)

### CODE REVIEW

**Comment by crimsonknave** [comment]
Left the comments in cuz I'm lazy and they could be useful for someone else.

I was able to confirm that it continues to work for me (with no post-login) screen, I can only assume that it works for you!

**Comment by bge-kernel-panic** [comment]
Well, yes. :)

Except for the messed up routing table, but there's not much I can do about that except fix it manually post login... :(

Oh and thanks for pulling this so quickly.

**Comment by crimsonknave** [comment]
No problem.

What sort of issues are you seeing with your routing table?

**Comment by bge-kernel-panic** [comment]
Well, I assume it's the way it's setup by the company... basically, default gateway is the VPN interface (so Internet traffic goes there), and some internal servers that I can ping can't be reached by SSH.  I really doubt it's the client's fault.

**Comment by crimsonknave** [comment]
Ah, fair.  Hope you can get it worked out!

**Pull request merged**
